name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name draco-china
          git config user.email draco.coder@gmail.com
          git add -A .
          git commit -m "generated"

      - name: Delete old workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          keep_minimum_runs: 1
          token: ${{ secrets.ACCESS_TOKEN }}